title: X: Supercharged Documentation
description: Documentation for X: Supercharged Chrome Extension - Mute content and share filters
baseurl: "/x-supercharged-docs"
url: "https://snieking.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal 